### ISSUE TITLE
I think you don't have the right script

### ISSUE THREAD

**Issue by Trojan7z7VZX** [hamukazu/lets-get-arrested#147]
The original script was: ```<script language="JavaScript">
for ( ; ; ) {
window.alert("　∧_∧　ババババ\n（ ・ω・)=つ≡つ\n（っ ≡つ=つ\n`/　　)\n(ノΠＵ\n何回閉じても無駄ですよ～ww\nm9（＾Д＾）プギャー！！\n　byソル (@0_Infinity_)")
}
</script>```

**Comment by davissorenson** [comment]
The Japanese README.ja.md says:
> ...以下のようなアラートの無限ループ...

Which, loosely translated, means:

> ...an infinite loop much like the [code] below...

I think the aim was to make the code easy to quickly comprehend.
