### ISSUE TITLE
For maximum impact, please create an NPM module.

### ISSUE THREAD

**Issue by didip** [hamukazu/lets-get-arrested#18]
This will help millions of Javascript developers to get arrested.

**Comment by origamium** [comment]
created. https://github.com/origamium/lets-get-arrested

npm module: https://www.npmjs.com/package/lets-get-arrested

Enjoy! And arrested!

**Comment by paulyc** [comment]
LGTM, ship it

**Comment by origamium** [comment]
will close #92
