### ISSUE TITLE
Feature suggestion: illegal number

### ISSUE THREAD

**Issue by paulyc** [hamukazu/lets-get-arrested#49]
If you add an illegal number, we'll all get arrested even faster. Of course this will vary (no pun intended) by jurisdiction. For those of us in the US, I believe an AACS master key will suffice. An image of Winnie the Pooh may do for China. Japan, umm, unblurred porn? Don't look at me for a PR, I haven't got any illegal numbers around here... *Whistles*

**Comment by Trung0246** [comment]
Hows about DeCSS?

**Comment by 1inguini** [comment]
I thought this project is some kind of protest to Japanese police, not American or Chinese police, so adding feature to get arrested by them may be inappropriate in my opinion.

**Comment by paulyc** [comment]
@1inguini I had assumed we were all getting arrested

**Comment by Faunsce** [comment]
@paulyc This is obviously a JP protest. Illegal numbers are illegal for good reason. This girl getting arrested was not for good reasons.

**Comment by paulyc** [comment]
Closing because nobody has a sense of humor
