### ISSUE TITLE
事実整理

### ISSUE THREAD

**Issue by kumack** [hamukazu/lets-get-arrested#6]
> 日本において、ある女子中学生が以下のようなアラートの無限ループを JavaScript で書いたとして警察に補導されました:

報道によれば、アラートの無限ループのJavaScriptが書かれた「URLを記述」したことによる補導ではないでしょうか。つまり、JavaScriptを書いた人は補導もなにもされていない。

**Comment by masa-kunikata** [comment]
gh_pages 向けの `https://hamukazu.github.io/` で始まる url を書かない限り、補導されないてことで、
README.md などにも意図的にその url を書いてないんでないすかね？

**Comment by pterodragon** [comment]
事実をちゃんと書きたいなら逮捕(arrest)ではなく、輔導または自宅捜索です

**Comment by hamukazu** [comment]
事実に合わせて書き換えました。
