### ISSUE TITLE
666，You are very six !

### ISSUE THREAD

**Issue by AibiTi** [hamukazu/lets-get-arrested#61]
666，You are very six !

**Comment by shuye02** [comment]
Umm, do you have any idea that 666 means the devil in a English-speaking culture?  
So, do please avoid using that

**Comment by shawniverson** [comment]
Spam, so says the spam man...

**Comment by robert-cronin** [comment]
It means awesome in Chinese, just depends on context my friend :) 六六六 厉害

**Comment by ZeroAurora** [comment]
@shuye02 666 means something like "you're so interesting" in Chinese culture.

**Comment by shuye02** [comment]
Thanks everyone, I know that because I speak Chinese  
I was thinking if it might be inappropriate to use Chinese Internet slangs in an English environment (plus, the phrase might lead to ambiguity among English speakers)  
But it seems like everyone knows Chinese slangs now. lol

**Comment by robert-cronin** [comment]
不懂这个网络用语的意思的人跟不上潮流了哈哈哈

**Comment by el-hoshino** [comment]
> But it seems like everyone knows Chinese slangs now. lol

I guess it's because everyone (except @shawniverson of course) leaving a comment here is Chinese. It still just looks like a spam for non-Chinese speakers, including the owner of this project. Plus, this is NOT an issue. Do you still remember deno?
https://www.jianshu.com/p/fcb2eddd9568

**Comment by shawniverson** [comment]
@el-hoshino Well now, I learn something new every day :smile: 六六六

**Comment by robert-cronin** [comment]
@el-hoshino I'm not Chinese just someone who understands Chinese culture :)

**Comment by chd123456** [comment]
666在中国是非常棒👍的意思。

**Comment by aikudexiaohai** [comment]
来了，老弟！

**Comment by KittyTang02** [comment]
> > But it seems like everyone knows Chinese slangs now. lol
> 
> I guess it's because everyone (except @shawniverson of course) leaving a comment here is Chinese. It still just looks like a spam for non-Chinese speakers, including the owner of this project. Plus, this is NOT an issue. Do you still remember deno?
> https://www.jianshu.com/p/fcb2eddd9568

Can't agree more. I thought of that disgusting issue in deno, too. Shame for @AibiTi

**Comment by Ryuurock** [comment]
一群魔鬼

**Comment by frostming** [comment]
@robert-cronin 跟语言没有关系，如果在一个多语言的环境，就避免使用一个可能引起误解的梗。更不能强求别人接受你的理解，并说别人out了。

「来了，老弟！」就没这个问题。

**Comment by sazima** [comment]
`666` means that you are excellent.

**Comment by freemember007** [comment]
poor quality of chinese.

**Comment by lazy1523** [comment]
> poor quality of chinese.

coordinate：beijing？？？

**Comment by Master76** [comment]
一个都被人玩烂得不行的话了，还当新鲜玩意儿把弄着玩儿呢，实属弟弟行为。

**Comment by shuye02** [comment]
@hamukazu I suggest closing this issue and lock conversation since it is completely off-topic

**Comment by ChungZH** [comment]
> @hamukazu I suggest closing this issue and lock conversation since it is completely off-topic

Agree, it's very boring. 🤨

**Comment by ChungZH** [comment]
@AibiTi 能主动点 close 这个 issue 吗？

**Comment by hamukazu** [comment]
I close this because I cannot understand most of the posts.
