### ISSUE TITLE
Get rid of unnecessary master branch

### ISSUE THREAD

**Issue by iczero** [hamukazu/lets-get-arrested#66]
It would be cleaner if there were only one branch (the gh-pages branch) instead of two separate branches both with an index.html file.
Commands to do so:
```shell
git push origin :gh-pages                # delete the old gh-pages branch
git branch -m master gh-pages            # create a new gh-pages branch from the master branch
git push origin :master                  # delete old master branch
git push --set-upstream origin gh-pages  # push new gh-pages branch
```

**Comment by yuta0801** [comment]
It also can set master as GitHub Pages branch

![image](https://user-images.githubusercontent.com/21266306/54082326-141a6280-4357-11e9-8d64-4ec634acc2fa.png)
