### ISSUE TITLE
Misleading links

### ISSUE THREAD

**Issue by yuta0801** [hamukazu/lets-get-arrested#80]
The URL "http://youraccount.github.io/lets-get-arrested" in README.md has linked automatically, but it isn't actually a usable link.

There is a person who is actually deceived in #67 (I think)

How about putting characters that are not URLs just `{}` to avoid automatic linking and to clarify that it needs to replace `youraccount`

http://youraccount.github.io/lets-get-arrested
↓
http://{youraccount}.github.io/lets-get-arrested

**Comment by hamukazu** [comment]
Agree.
