### ISSUE TITLE
The cops won't gonna book me on this

### ISSUE THREAD

**Issue by mraandtux** [hamukazu/lets-get-arrested#85]
I created a page based on this repo, along with **surprising** messages. I bet the cops in Japan won't book me! ([I don't wanna end up like this guy](https://www.hongkongfp.com/2018/12/14/hong-kong-activist-faces-prosecution-japan-burning-props-outside-shrine-says-lawmaker/))
https://mraandtux.github.io/neverforget/
([Credits included](https://github.com/mraandtux/mraandtux.github.com/tree/master/neverforget))

**Comment by happyZYM** [comment]
> 
> 
> I created a page based on this repo, along with **surprising** messages. I bet the cops in Japan won't book me! ([I don't wanna end up like this guy](https://www.hongkongfp.com/2018/12/14/hong-kong-activist-faces-prosecution-japan-burning-props-outside-shrine-says-lawmaker/))
> https://mraandtux.github.io/neverforget/
> ([Credits included](https://github.com/mraandtux/mraandtux.github.com/tree/master/neverforget))

建议你把中文的改一下，好像骂了一些无辜人。。。

**Comment by Ragnokii** [comment]
> 
> 
> I created a page based on this repo, along with **surprising** messages. I bet the cops in Japan won't book me! ([I don't wanna end up like this guy](https://www.hongkongfp.com/2018/12/14/hong-kong-activist-faces-prosecution-japan-burning-props-outside-shrine-says-lawmaker/))
> https://mraandtux.github.io/neverforget/
> ([Credits included](https://github.com/mraandtux/mraandtux.github.com/tree/master/neverforget))



> 
> 
> > I created a page based on this repo, along with **surprising** messages. I bet the cops in Japan won't book me! ([I don't wanna end up like this guy](https://www.hongkongfp.com/2018/12/14/hong-kong-activist-faces-prosecution-japan-burning-props-outside-shrine-says-lawmaker/))
> > https://mraandtux.github.io/neverforget/
> > ([Credits included](https://github.com/mraandtux/mraandtux.github.com/tree/master/neverforget))
> 
> 建议你把中文部分改一下，好像骂了一些无辜人。。。

把"建议"和"好像"去掉

**Comment by happyZYM** [comment]
@Ragnokii Sorry，个人语言习惯，请见谅。。。

**Comment by Ragnokii** [comment]
@happyZYM没，我不是在杠你，只是刚才点进去后被刺激到了,Sorry- -
